// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nowplaying_webapp.Models;

#nullable disable

namespace nowplaying_webapp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329165837_HyprlandMixxxEnabled")]
    partial class HyprlandMixxxEnabled
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("nowplaying_webapp.Models.ConfigModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DemoDataEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HyprlandMixxxEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JellyfinApi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("JellyfinEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JellyfinUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlexApi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PlexEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlexUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configs");
                });
#pragma warning restore 612, 618
        }
    }
}
